# SPDX-License-Identifier: LGPL-2.1-or-later
# Copyright (c) 2025 DBZero Software sp. z o.o.

import asyncio
from concurrent.futures import ThreadPoolExecutor
from dataclasses import dataclass
from contextvars import ContextVar

import dbzero as db0
import pytest

from .conftest import DB0_DIR


@db0.enum(values=["CREATE", "READ", "UPDATE", "DELETE"])
class FieldAccess:
    pass


@db0.memo(protect_fields=True)
@dataclass
class MemoProtectedFieldsClass:
    name: str
    value: int


@db0.memo(protect_fields=True)
@dataclass
class MemoProtectedComplexFieldsClass:
    none_value: object
    flag: bool
    count: int
    name: str
    payload: bytes
    pair: tuple


@db0.memo(protect_fields=True)
@dataclass
class MemoProtectedDefaultFieldsClass:
    name: str
    generated_value: str = "auto-generated"


@db0.memo(protect_fields=True)
class MemoProtectedAutoGeneratedInitVarClass:
    generated_value = "auto-generated"

    def __init__(self, name, include_generated=False):
        self.name = name
        if include_generated:
            self.generated_value = "persisted"


@db0.memo
@dataclass
class MemoUnprotectedFieldsClass:
    name: str
    value: int


@db0.memo(protect_fields=True)
class MemoProtectedDynamicFieldsClass:
    def __init__(self, count):
        for i in range(count):
            setattr(self, f"field_{i}", i)


@db0.memo(protect_fields=True)
class MemoProtectedManyInitFieldsClass:
    def __init__(self, count):
        values = (
            lambda i: i,
            lambda i: bool(i % 2),
            lambda i: f"value-{i}",
            lambda i: i / 10,
            lambda i: bytes([i % 256]),
            lambda i: (i, f"tuple-{i}"),
        )
        for i in range(count):
            setattr(self, f"init_field_{i}", values[i % len(values)](i))


@db0.memo
@dataclass
class MemoUnprotectedBaseFieldsClass:
    base_value: str


@db0.memo(protect_fields=True)
@dataclass
class MemoProtectedDerivedFieldsClass(MemoUnprotectedBaseFieldsClass):
    name: str
    value: int


@db0.memo
@dataclass
class MemoImplicitlyProtectedDerivedFieldsClass(MemoProtectedDerivedFieldsClass):
    derived_value: float


def get_memo_class_object(obj):
    return db0.get_memo_class(obj).get_class()


def test_protect_fields_defaults_to_false(db0_fixture):
    obj = MemoUnprotectedFieldsClass("alpha", 1)
    assert get_memo_class_object(obj).get_type_flags()["protect_fields"] is False
    description = db0.describe(obj)
    assert description["protected_fields"] is False
    assert description["field_offset_range"] == 0


def test_protect_fields_is_persisted_on_class(db0_fixture):
    obj = MemoProtectedFieldsClass("alpha", 1)
    flags = get_memo_class_object(obj).get_type_flags()
    assert flags["protect_fields"] is True
    assert flags["singleton"] is False
    assert flags["no_default_tags"] is False
    assert flags["immutable"] is False
    description = db0.describe(obj)
    assert description["protected_fields"] is True
    assert description["field_offset_range"] > 0


def test_protect_fields_survives_redecoration_without_parameter(db0_fixture):
    @db0.memo(id="dbzero-software/dbzero/tests/protected-redecorated", protect_fields=True)
    @dataclass
    class ProtectedBefore:
        name: str

    obj = ProtectedBefore("alpha")
    obj_id = db0.uuid(obj)
    assert get_memo_class_object(obj).get_type_flags()["protect_fields"] is True
    db0.commit()

    db0.close()
    db0.init(DB0_DIR)
    db0.open("my-test-prefix")

    @db0.memo(id="dbzero-software/dbzero/tests/protected-redecorated")
    @dataclass
    class ProtectedAfter:
        name: str

    obj = db0.fetch(ProtectedAfter, obj_id)
    assert get_memo_class_object(obj).get_type_flags()["protect_fields"] is True


def test_explicit_false_does_not_unprotect_materialized_class(db0_fixture):
    @db0.memo(id="dbzero-software/dbzero/tests/protected-explicit-false", protect_fields=True)
    @dataclass
    class ProtectedBefore:
        name: str

    obj = ProtectedBefore("alpha")
    obj_id = db0.uuid(obj)
    assert get_memo_class_object(obj).get_type_flags()["protect_fields"] is True
    db0.commit()

    db0.close()
    db0.init(DB0_DIR)
    db0.open("my-test-prefix")

    @db0.memo(id="dbzero-software/dbzero/tests/protected-explicit-false", protect_fields=False)
    @dataclass
    class ProtectedAfter:
        name: str

    obj = db0.fetch(ProtectedAfter, obj_id)
    assert get_memo_class_object(obj).get_type_flags()["protect_fields"] is True


def test_protect_fields_can_be_enabled_after_class_materialization(db0_fixture):
    @db0.memo(id="dbzero-software/dbzero/tests/protected-enabled-later")
    @dataclass
    class ProtectedBefore:
        name: str

    obj = ProtectedBefore("alpha")
    obj_id = db0.uuid(obj)
    assert get_memo_class_object(obj).get_type_flags()["protect_fields"] is False
    db0.commit()

    db0.close()
    db0.init(DB0_DIR)
    db0.open("my-test-prefix")

    @db0.memo(id="dbzero-software/dbzero/tests/protected-enabled-later", protect_fields=True)
    @dataclass
    class ProtectedAfter:
        name: str

    obj = db0.fetch(ProtectedAfter, obj_id)
    assert get_memo_class_object(obj).get_type_flags()["protect_fields"] is True


def test_reset_protect_fields_rejects_type_still_decorated_as_protected(db0_fixture):
    MemoProtectedFieldsClass("alpha", 1)

    with pytest.raises(RuntimeError, match="decorated.*protect_fields"):
        db0.reset_protect_fields(MemoProtectedFieldsClass)


def test_reset_protect_fields_clears_persisted_flag_after_decorator_removed(db0_fixture):
    @db0.memo(id="dbzero-software/dbzero/tests/protected-reset", protect_fields=True)
    @dataclass
    class ProtectedBefore:
        name: str

    obj = ProtectedBefore("alpha")
    obj_id = db0.uuid(obj)
    assert get_memo_class_object(obj).get_type_flags()["protect_fields"] is True
    db0.commit()

    db0.close()
    db0.init(DB0_DIR)
    db0.open("my-test-prefix")

    @db0.memo(id="dbzero-software/dbzero/tests/protected-reset", protect_fields=False)
    @dataclass
    class ProtectedAfter:
        name: str

    obj = db0.fetch(ProtectedAfter, obj_id)
    memo_class = get_memo_class_object(obj)
    assert memo_class.get_type_flags()["protect_fields"] is True

    assert db0.reset_protect_fields(ProtectedAfter) is None
    assert memo_class.get_type_flags()["protect_fields"] is False


def test_set_field_access_accepts_single_and_multiple_accounts(db0_fixture):
    MemoProtectedFieldsClass("alpha", 1)

    db0.set_field_access(MemoProtectedFieldsClass, 123, (FieldAccess.READ,), "name")
    db0.set_field_access(
        MemoProtectedFieldsClass,
        [123, 456],
        (FieldAccess.CREATE, FieldAccess.UPDATE),
        "name",
        "value",
    )


def test_set_field_access_accepts_empty_mode_to_clear(db0_fixture):
    MemoProtectedFieldsClass("alpha", 1)

    db0.set_field_access(MemoProtectedFieldsClass, 123, (), "name")


def test_set_field_access_requires_protected_class(db0_fixture):
    MemoUnprotectedFieldsClass("alpha", 1)

    try:
        db0.set_field_access(MemoUnprotectedFieldsClass, 123, (FieldAccess.READ,), "name")
    except Exception as exc:
        assert "protected fields" in str(exc)
    else:
        assert False, "set_field_access should fail for unprotected classes"


def test_protect_fields_is_inherited_by_derived_memo_classes(db0_fixture):
    obj = MemoImplicitlyProtectedDerivedFieldsClass("base", "alpha", 1, 1.5)

    assert get_memo_class_object(obj).get_type_flags()["protect_fields"] is True
    db0.set_field_access(MemoImplicitlyProtectedDerivedFieldsClass, 123, (FieldAccess.READ,), "derived_value")


def test_protect_fields_cannot_be_disabled_in_derived_memo_class(db0_fixture):
    with pytest.raises(RuntimeError, match="protect_fields.*base"):
        @db0.memo(protect_fields=False)
        @dataclass
        class ExplicitlyUnprotectedDerived(MemoProtectedDerivedFieldsClass):
            extra_value: str


def test_set_field_access_still_rejects_unprotected_base_of_protected_class(db0_fixture):
    MemoImplicitlyProtectedDerivedFieldsClass("base", "alpha", 1, 1.5)

    with pytest.raises(RuntimeError, match="protected fields"):
        db0.set_field_access(MemoUnprotectedBaseFieldsClass, 123, (FieldAccess.READ,), "base_value")


def test_reset_protect_fields_rejects_inherited_protection(db0_fixture):
    obj = MemoImplicitlyProtectedDerivedFieldsClass("base", "alpha", 1, 1.5)
    memo_class = get_memo_class_object(obj)

    with pytest.raises(RuntimeError, match="inherits.*protect_fields"):
        db0.reset_protect_fields(MemoImplicitlyProtectedDerivedFieldsClass)

    assert memo_class.get_type_flags()["protect_fields"] is True


def test_class_reset_protect_fields_rejects_inherited_protection(db0_fixture):
    obj = MemoImplicitlyProtectedDerivedFieldsClass("base", "alpha", 1, 1.5)
    memo_class = get_memo_class_object(obj)

    with pytest.raises(RuntimeError, match="inherits.*protect_fields"):
        memo_class.reset_protect_fields()

    assert memo_class.get_type_flags()["protect_fields"] is True


def test_explicit_true_is_allowed_on_class_derived_from_protected_base(db0_fixture):
    @db0.memo(protect_fields=True)
    @dataclass
    class ExplicitlyProtectedDerived(MemoProtectedDerivedFieldsClass):
        extra_value: str

    obj = ExplicitlyProtectedDerived("base", "alpha", 1, "extra")

    assert get_memo_class_object(obj).get_type_flags()["protect_fields"] is True
    db0.set_field_access(ExplicitlyProtectedDerived, 123, (FieldAccess.READ,), "extra_value")


def test_set_field_access_accepts_unknown_field_names(db0_fixture):
    MemoProtectedFieldsClass("alpha", 1)

    db0.set_field_access(MemoProtectedFieldsClass, 123, (FieldAccess.READ,), "missing")


def test_get_field_access_returns_assigned_masks(db0_fixture):
    MemoProtectedFieldsClass("alpha", 1)
    db0.set_field_access(MemoProtectedFieldsClass, 123, (FieldAccess.READ,), "name")
    db0.set_field_access(
        MemoProtectedFieldsClass,
        123,
        (FieldAccess.CREATE, FieldAccess.UPDATE),
        "value",
    )

    result = dict(db0.get_field_access(MemoProtectedFieldsClass, 123))

    assert result["name"] == ("READ",)
    assert result["value"] == ("CREATE", "UPDATE")


def test_get_field_access_returns_empty_mask_after_clear(db0_fixture):
    MemoProtectedFieldsClass("alpha", 1)
    db0.set_field_access(MemoProtectedFieldsClass, 123, (), "name")

    result = dict(db0.get_field_access(MemoProtectedFieldsClass, 123))

    assert result["name"] == ()


def test_get_field_access_returns_predeclared_and_later_materialized_field(db0_fixture):
    obj = MemoProtectedFieldsClass("alpha", 1)
    expected = {
        "missing_a": ("READ",),
        "missing_b": ("CREATE", "UPDATE"),
        "missing_c": ("DELETE",),
    }
    db0.set_field_access(MemoProtectedFieldsClass, 123, (FieldAccess.READ,), "missing_a")
    db0.set_field_access(
        MemoProtectedFieldsClass,
        123,
        (FieldAccess.CREATE, FieldAccess.UPDATE),
        "missing_b",
    )
    db0.set_field_access(MemoProtectedFieldsClass, 123, (FieldAccess.DELETE,), "missing_c")

    predeclared = dict(db0.get_field_access(MemoProtectedFieldsClass, 123))
    for field_name, mask in expected.items():
        assert predeclared[field_name] == mask

    for index, field_name in enumerate(expected):
        setattr(obj, field_name, index)
        materialized = dict(db0.get_field_access(MemoProtectedFieldsClass, 123))
        for expected_field_name, mask in expected.items():
            assert materialized[expected_field_name] == mask


def test_get_field_access_returns_empty_for_unknown_account(db0_fixture):
    MemoProtectedFieldsClass("alpha", 1)

    assert list(db0.get_field_access(MemoProtectedFieldsClass, 999)) == []


def test_describe_field_offset_range_stays_constrained_for_many_fields(db0_fixture):
    field_count = 512
    total_field_count = field_count * 2
    obj = MemoProtectedDynamicFieldsClass(field_count)
    initial_range = db0.describe(obj)["field_offset_range"]

    assert db0.describe(obj)["protected_fields"] is True
    assert initial_range < field_count * 8

    for i in range(field_count, field_count * 2):
        setattr(obj, f"field_{i}", i)

    dynamic_range = db0.describe(obj)["field_offset_range"]
    assert dynamic_range < total_field_count * 2 + 128


def test_describe_field_offset_range_stays_constrained_for_many_init_fields_with_various_types(db0_fixture):
    field_count = 768
    obj = MemoProtectedManyInitFieldsClass(field_count)

    description = db0.describe(obj)

    assert description["protected_fields"] is True
    assert description["field_offset_range"] < field_count * 2 + 128


def test_describe_field_offset_range_counts_predeclared_access_fields(db0_fixture):
    obj = MemoProtectedDynamicFieldsClass(3)
    baseline_range = db0.describe(obj)["field_offset_range"]

    for i in range(120):
        db0.set_field_access(
            MemoProtectedDynamicFieldsClass,
            123,
            (FieldAccess.READ,),
            f"future_field_{i}",
        )

    predeclared_range = db0.describe(obj)["field_offset_range"]
    assert predeclared_range > baseline_range
    assert predeclared_range < 256

    for i in range(120):
        setattr(obj, f"future_field_{i}", i)

    materialized_range = db0.describe(obj)["field_offset_range"]
    assert materialized_range >= predeclared_range
    assert materialized_range < 120 * 2 + 128


def test_protected_field_getter_requires_initialized_data_masking(db0_fixture):
    obj = MemoProtectedFieldsClass("alpha", 1)

    with pytest.raises(RuntimeError, match="data masking"):
        _ = obj.name


def test_protected_field_create_from_init_requires_create_access(db0_fixture):
    account_id = ContextVar("protected_create_init_account_id")
    MemoProtectedFieldsClass("materializer", 0)
    db0.set_field_access(MemoProtectedFieldsClass, 101, (FieldAccess.CREATE,), "name")
    db0.set_field_access(
        MemoProtectedFieldsClass,
        202,
        (FieldAccess.CREATE,),
        "name",
        "value",
    )
    db0._init_data_masking(account_id)

    account_id.set(101)
    with pytest.raises(PermissionError, match="create"):
        MemoProtectedFieldsClass("alpha", 1)

    account_id.set(202)
    MemoProtectedFieldsClass("beta", 2)


def test_protected_field_create_from_init_uses_predeclared_name_masks(db0_fixture):
    account_id = ContextVar("protected_create_predeclared_account_id")

    @db0.memo(protect_fields=True)
    class InitFutureField:
        def __init__(self, include_fields=False):
            if include_fields:
                self.future = "allowed"
                self.denied = "blocked"

    InitFutureField()
    db0.set_field_access(InitFutureField, 101, (FieldAccess.CREATE,), "future")
    db0._init_data_masking(account_id)

    account_id.set(101)
    with pytest.raises(PermissionError, match="create"):
        InitFutureField(include_fields=True)


def test_protected_field_append_requires_create_access(db0_fixture):
    account_id = ContextVar("protected_create_append_account_id")
    obj = MemoProtectedFieldsClass("alpha", 1)
    db0.set_field_access(MemoProtectedFieldsClass, 101, (FieldAccess.UPDATE,), "extra")
    db0.set_field_access(MemoProtectedFieldsClass, 202, (FieldAccess.CREATE,), "extra")
    db0._init_data_masking(account_id)

    account_id.set(101)
    with pytest.raises(PermissionError, match="create"):
        obj.extra = "denied"

    account_id.set(202)
    obj.extra = "allowed"


def test_protected_field_update_does_not_require_create_access(db0_fixture):
    account_id = ContextVar("protected_update_existing_account_id")
    obj = MemoProtectedFieldsClass("alpha", 1)
    db0.set_field_access(MemoProtectedFieldsClass, 101, (FieldAccess.UPDATE,), "name")
    db0._init_data_masking(account_id)

    account_id.set(101)
    obj.name = "beta"


def test_protected_field_update_requires_update_access(db0_fixture):
    account_id = ContextVar("protected_update_denied_account_id")
    obj = MemoProtectedFieldsClass("alpha", 1)
    db0.set_field_access(MemoProtectedFieldsClass, 101, (FieldAccess.READ,), "name")
    db0.set_field_access(MemoProtectedFieldsClass, 202, (FieldAccess.READ, FieldAccess.UPDATE), "name")
    db0._init_data_masking(account_id)

    account_id.set(101)
    with pytest.raises(PermissionError, match="update"):
        obj.name = "denied"
    assert obj.name == "alpha"

    account_id.set(202)
    obj.name = "allowed"
    assert obj.name == "allowed"


def test_protected_field_update_requires_initialized_data_masking(db0_fixture):
    obj = MemoProtectedFieldsClass("alpha", 1)

    with pytest.raises(RuntimeError, match="data masking"):
        obj.name = "beta"


def test_protected_field_update_allows_debug_full_access_super_account(db0_fixture):
    account_id = ContextVar("protected_update_debug_full_access_account_id")
    obj = MemoProtectedFieldsClass("alpha", 1)
    db0._init_data_masking(account_id, mode="DEBUG")
    account_id.set(-2)

    obj.name = "beta"
    assert obj.name == "beta"


def test_protected_field_update_rejects_debug_read_only_super_account(db0_fixture):
    account_id = ContextVar("protected_update_debug_read_only_account_id")
    obj = MemoProtectedFieldsClass("alpha", 1)
    db0._init_data_masking(account_id, mode="DEBUG")
    account_id.set(-1)

    with pytest.raises(PermissionError, match="update"):
        obj.name = "beta"
    assert obj.name == "alpha"


def test_protected_field_delete_requires_delete_access(db0_fixture):
    account_id = ContextVar("protected_delete_account_id")
    obj = MemoProtectedFieldsClass("alpha", 1)
    db0.set_field_access(MemoProtectedFieldsClass, 101, (FieldAccess.READ, FieldAccess.UPDATE), "name")
    db0.set_field_access(MemoProtectedFieldsClass, 202, (FieldAccess.READ, FieldAccess.DELETE), "name")
    db0._init_data_masking(account_id)

    account_id.set(101)
    with pytest.raises(PermissionError, match="delete"):
        del obj.name
    assert obj.name == "alpha"

    account_id.set(202)
    del obj.name
    with pytest.raises(AttributeError):
        _ = obj.name


def test_protected_field_getter_requires_read_access(db0_fixture):
    account_id = ContextVar("protected_read_account_id")
    obj = MemoProtectedFieldsClass("alpha", 1)
    db0.set_field_access(MemoProtectedFieldsClass, 123, (FieldAccess.READ,), "name")
    db0._init_data_masking(account_id)
    account_id.set(123)

    assert obj.name == "alpha"

    with pytest.raises(PermissionError, match="read"):
        _ = obj.value


def test_protected_field_getter_does_not_inherit_base_class_masks(db0_fixture):
    account_id = ContextVar("protected_inheritance_account_id")
    obj = MemoImplicitlyProtectedDerivedFieldsClass("base", "alpha", 1, 1.5)
    db0.set_field_access(MemoProtectedDerivedFieldsClass, 123, (FieldAccess.READ,), "base_value", "name")
    db0.set_field_access(MemoImplicitlyProtectedDerivedFieldsClass, 123, (FieldAccess.READ,), "derived_value")
    db0._init_data_masking(account_id)
    account_id.set(123)

    assert obj.derived_value == 1.5
    with pytest.raises(PermissionError, match="read"):
        _ = obj.base_value
    with pytest.raises(PermissionError, match="read"):
        _ = obj.name
    with pytest.raises(PermissionError, match="read"):
        _ = obj.value


def test_protected_field_getter_uses_derived_class_own_masks(db0_fixture):
    account_id = ContextVar("protected_inheritance_allow_override_account_id")
    obj = MemoImplicitlyProtectedDerivedFieldsClass("base", "alpha", 1, 1.5)
    db0.set_field_access(MemoProtectedDerivedFieldsClass, 123, (), "name")
    db0.set_field_access(MemoImplicitlyProtectedDerivedFieldsClass, 123, (FieldAccess.READ,), "name")
    db0._init_data_masking(account_id)
    account_id.set(123)

    assert obj.name == "alpha"
    with pytest.raises(PermissionError, match="read"):
        _ = obj.value


def test_inherited_protect_fields_survives_reopen_without_parameter(db0_fixture):
    @db0.memo(id="dbzero-software/dbzero/tests/protected-inherited-reopen-base")
    @dataclass
    class ReopenBase:
        base_value: str

    @db0.memo(id="dbzero-software/dbzero/tests/protected-inherited-reopen-mid", protect_fields=True)
    @dataclass
    class ReopenMid(ReopenBase):
        name: str

    @db0.memo(id="dbzero-software/dbzero/tests/protected-inherited-reopen-derived")
    @dataclass
    class ReopenDerived(ReopenMid):
        value: int

    obj = ReopenDerived("base", "alpha", 1)
    obj_id = db0.uuid(obj)
    assert get_memo_class_object(obj).get_type_flags()["protect_fields"] is True
    db0.commit()

    db0.close()
    db0.init(DB0_DIR)
    db0.open("my-test-prefix")

    @db0.memo(id="dbzero-software/dbzero/tests/protected-inherited-reopen-base")
    @dataclass
    class ReopenBaseAfter:
        base_value: str

    @db0.memo(id="dbzero-software/dbzero/tests/protected-inherited-reopen-mid")
    @dataclass
    class ReopenMidAfter(ReopenBaseAfter):
        name: str

    @db0.memo(id="dbzero-software/dbzero/tests/protected-inherited-reopen-derived")
    @dataclass
    class ReopenDerivedAfter(ReopenMidAfter):
        value: int

    obj = db0.fetch(ReopenDerivedAfter, obj_id)
    assert get_memo_class_object(obj).get_type_flags()["protect_fields"] is True
    db0.set_field_access(ReopenDerivedAfter, 123, (FieldAccess.READ,), "value")


def test_derived_class_inherits_protect_fields_enabled_on_base_after_materialization(db0_fixture):
    @db0.memo(id="dbzero-software/dbzero/tests/protected-base-enabled-later-base")
    @dataclass
    class BaseBefore:
        base_value: str

    @db0.memo(id="dbzero-software/dbzero/tests/protected-base-enabled-later-derived")
    @dataclass
    class DerivedBefore(BaseBefore):
        value: int

    obj = DerivedBefore("base", 1)
    obj_id = db0.uuid(obj)
    assert get_memo_class_object(obj).get_type_flags()["protect_fields"] is False
    with pytest.raises(RuntimeError, match="protected fields"):
        db0.set_field_access(DerivedBefore, 123, (FieldAccess.READ,), "value")
    db0.commit()

    db0.close()
    db0.init(DB0_DIR)
    db0.open("my-test-prefix")

    @db0.memo(id="dbzero-software/dbzero/tests/protected-base-enabled-later-base", protect_fields=True)
    @dataclass
    class BaseAfter:
        base_value: str

    @db0.memo(id="dbzero-software/dbzero/tests/protected-base-enabled-later-derived")
    @dataclass
    class DerivedAfter(BaseAfter):
        value: int

    obj = db0.fetch(DerivedAfter, obj_id)
    assert get_memo_class_object(obj).get_type_flags()["protect_fields"] is True
    db0.set_field_access(DerivedAfter, 123, (FieldAccess.READ,), "value")


def test_derived_class_stops_inheriting_protect_fields_after_base_reset(db0_fixture):
    @db0.memo(id="dbzero-software/dbzero/tests/protected-base-reset-base", protect_fields=True)
    @dataclass
    class BaseBefore:
        base_value: str

    @db0.memo(id="dbzero-software/dbzero/tests/protected-base-reset-derived")
    @dataclass
    class DerivedBefore(BaseBefore):
        value: int

    obj = DerivedBefore("base", 1)
    obj_id = db0.uuid(obj)
    assert get_memo_class_object(obj).get_type_flags()["protect_fields"] is True
    db0.commit()

    db0.close()
    db0.init(DB0_DIR)
    db0.open("my-test-prefix")

    @db0.memo(id="dbzero-software/dbzero/tests/protected-base-reset-base", protect_fields=False)
    @dataclass
    class BaseAfter:
        base_value: str

    @db0.memo(id="dbzero-software/dbzero/tests/protected-base-reset-derived")
    @dataclass
    class DerivedAfter(BaseAfter):
        value: int

    obj = db0.fetch(DerivedAfter, obj_id)
    db0.reset_protect_fields(BaseAfter)

    assert get_memo_class_object(obj).get_type_flags()["protect_fields"] is False
    with pytest.raises(RuntimeError, match="protected fields"):
        db0.set_field_access(DerivedAfter, 123, (FieldAccess.READ,), "value")


def test_protected_field_getter_returns_missing_value_placeholder(db0_fixture):
    account_id = ContextVar("protected_placeholder_account_id")
    missing_value = object()
    obj = MemoProtectedFieldsClass("alpha", 1)
    db0.set_field_access(MemoProtectedFieldsClass, 123, (FieldAccess.READ,), "name")
    db0._init_data_masking(account_id, missing_value_placeholder=missing_value)
    account_id.set(123)

    assert obj.value is missing_value


def test_protected_field_getter_allows_debug_super_account_read(db0_fixture):
    account_id = ContextVar("protected_super_account_id")
    obj = MemoProtectedFieldsClass("alpha", 1)
    db0._init_data_masking(account_id, mode="DEBUG")
    account_id.set(-1)

    assert obj.name == "alpha"
    assert obj.value == 1


def test_protected_field_getter_rejects_invalid_negative_account_id(db0_fixture):
    account_id = ContextVar("protected_invalid_account_id")
    obj = MemoProtectedFieldsClass("alpha", 1)
    db0._init_data_masking(account_id, mode="DEBUG")
    account_id.set(-3)

    with pytest.raises(RuntimeError, match="invalid.*account"):
        _ = obj.name


def test_protected_field_getter_enforces_read_access_for_auto_generated_fields(db0_fixture):
    account_id = ContextVar("protected_auto_generated_account_id")
    MemoProtectedAutoGeneratedInitVarClass("materializer", include_generated=True)
    obj = MemoProtectedAutoGeneratedInitVarClass("alpha")
    db0.set_field_access(MemoProtectedAutoGeneratedInitVarClass, 101, (FieldAccess.READ,), "name")
    db0.set_field_access(MemoProtectedAutoGeneratedInitVarClass, 202, (FieldAccess.READ,), "generated_value")
    db0._init_data_masking(account_id)

    account_id.set(101)
    assert obj.name == "alpha"
    with pytest.raises(PermissionError, match="read"):
        _ = obj.generated_value

    account_id.set(202)
    assert obj.generated_value == "auto-generated"
    with pytest.raises(PermissionError, match="read"):
        _ = obj.name


def test_protected_field_getter_applies_complex_masks_for_mixed_field_types(db0_fixture):
    account_id = ContextVar("protected_complex_account_id")
    obj = MemoProtectedComplexFieldsClass(None, False, 7, "alpha", b"payload", ("x", 11))

    db0.set_field_access(
        MemoProtectedComplexFieldsClass,
        101,
        (FieldAccess.READ,),
        "none_value",
        "flag",
        "name",
    )
    db0.set_field_access(
        MemoProtectedComplexFieldsClass,
        202,
        (FieldAccess.READ,),
        "count",
        "payload",
    )
    db0.set_field_access(
        MemoProtectedComplexFieldsClass,
        303,
        (FieldAccess.READ,),
        "none_value",
        "flag",
        "count",
        "name",
        "payload",
        "pair",
    )
    db0._init_data_masking(account_id)

    account_id.set(101)
    assert obj.none_value is None
    assert obj.flag is False
    assert obj.name == "alpha"
    with pytest.raises(PermissionError, match="read"):
        _ = obj.count
    with pytest.raises(PermissionError, match="read"):
        _ = obj.payload

    account_id.set(202)
    assert obj.count == 7
    assert obj.payload == b"payload"
    with pytest.raises(PermissionError, match="read"):
        _ = obj.none_value
    with pytest.raises(PermissionError, match="read"):
        _ = obj.flag

    account_id.set(303)
    assert obj.none_value is None
    assert obj.flag is False
    assert obj.count == 7
    assert obj.name == "alpha"
    assert obj.payload == b"payload"
    assert obj.pair == ("x", 11)

    account_id.set(404)
    for field_name in ("none_value", "flag", "count", "name", "payload", "pair"):
        with pytest.raises(PermissionError, match="read"):
            getattr(obj, field_name)


@pytest.mark.asyncio
async def test_protected_field_getter_uses_contextvar_per_async_task(db0_fixture):
    account_id = ContextVar("protected_async_account_id")
    obj = MemoProtectedFieldsClass("alpha", 1)
    db0.set_field_access(MemoProtectedFieldsClass, 101, (FieldAccess.READ,), "name")
    db0.set_field_access(MemoProtectedFieldsClass, 202, (FieldAccess.READ,), "value")
    db0._init_data_masking(account_id)

    async def read_as(account, allowed_field, denied_field):
        account_id.set(account)
        await asyncio.sleep(0)
        allowed_value = getattr(obj, allowed_field)
        await asyncio.sleep(0)
        with pytest.raises(PermissionError, match="read"):
            getattr(obj, denied_field)
        return allowed_value

    name_value, int_value = await asyncio.gather(
        read_as(101, "name", "value"),
        read_as(202, "value", "name"),
    )

    assert name_value == "alpha"
    assert int_value == 1


def test_protected_field_getter_uses_contextvar_per_thread(db0_fixture):
    account_id = ContextVar("protected_thread_account_id")
    obj = MemoProtectedComplexFieldsClass(None, True, 7, "alpha", b"payload", ("x", 11))
    db0.set_field_access(
        MemoProtectedComplexFieldsClass,
        101,
        (FieldAccess.READ,),
        "none_value",
        "flag",
    )
    db0.set_field_access(
        MemoProtectedComplexFieldsClass,
        202,
        (FieldAccess.READ,),
        "count",
        "name",
    )
    db0._init_data_masking(account_id)

    def read_as(account):
        account_id.set(account)
        if account == 101:
            with pytest.raises(PermissionError, match="read"):
                _ = obj.count
            return obj.none_value, obj.flag
        with pytest.raises(PermissionError, match="read"):
            _ = obj.flag
        return obj.count, obj.name

    with ThreadPoolExecutor(max_workers=2) as pool:
        account_101 = pool.submit(read_as, 101)
        account_202 = pool.submit(read_as, 202)

    assert account_101.result() == (None, True)
    assert account_202.result() == (7, "alpha")
