[build-system]
build-backend = 'mesonpy'
requires = ['meson-python']

[project]
name = 'dbzero'
version = '0.6.2'
description = 'DISTIC (Durable, Infinite, Shared, Transactional, Isolated, Composable) storage system for Python 3.x offering flexibility of a memory with durability of a database.'
readme = 'README.md'
requires-python = '>=3.9'
license = {file = 'LICENSE'}
authors = [
     { name = 'Wojciech Sebastian Kozlowski', email='info@dbzero.io' },
]
dependencies = [
    'fasteners==0.19'
]

classifiers = [
    'Programming Language :: Python :: 3',
    'Programming Language :: Python :: 3 :: Only',
]

[project.urls]
homepage = 'https://dbzero.io/'
documentation = 'https://docs.dbzero.io/'
repository = 'https://github.com/dbzero-software/dbzero'


[tool.pytest.ini_options]
testpaths = ["python_tests"]
