// SPDX-License-Identifier: LGPL-2.1-or-later
// Copyright (c) 2025 DBZero Software sp. z o.o.

#include "ObjectImmutableImpl.hpp"

#include <dbzero/bindings/python/PyToolkit.hpp>
#include <dbzero/core/exception/Exceptions.hpp>
#include <dbzero/object_model/class/Class.hpp>

namespace db0::object_model

{
    GC0_Define(ObjectImmutableImpl)

    ObjectImmutableImpl::ObjectSharedPtr ObjectImmutableImpl::tryGet(
        MemberLoc memberLoc, bool *isAutoGenerated
    ) const
    {
        bool baseIsAutoGenerated = false;
        auto result = super_t::tryGet(memberLoc, &baseIsAutoGenerated);
        if (result.get() && !baseIsAutoGenerated) {
            if (isAutoGenerated) {
                *isAutoGenerated = false;
            }
            return result;
        }

        const auto &memberId = memberLoc.first;
        if (!memberId) {
            if (result.get() && isAutoGenerated) {
                *isAutoGenerated = baseIsAutoGenerated;
            }
            return result;
        }

        for (const auto &fieldInfo: memberId) {
            auto object = tryGetEmbeddedField(fieldInfo);
            if (object.get()) {
                if (isAutoGenerated) {
                    *isAutoGenerated = false;
                }
                return object;
            }
        }

        if (result.get() && isAutoGenerated) {
            *isAutoGenerated = baseIsAutoGenerated;
        }
        return result;
    }

    ObjectImmutableImpl::ObjectSharedPtr ObjectImmutableImpl::tryGet(
        const char *fieldName, bool *isAutoGenerated
    ) const
    {
        return tryGet(this->findField(fieldName), isAutoGenerated);
    }

    ObjectImmutableImpl::ObjectSharedPtr ObjectImmutableImpl::tryGetEmbeddedField(
        const FieldInfo &fieldInfo
    ) const
    {
        const auto &[fieldId, fidelity] = fieldInfo;
        if (!fieldId || fidelity != 0) {
            return {};
        }

        if (this->hasInstance()) {
            auto *embeddedValue = (*this)->variableValue(fieldId.getIndex());
            return embeddedValue ? python::PyToolkit::unloadEmbeddedInstance(*embeddedValue) : ObjectSharedPtr();
        }

        auto *initializer = dynamic_cast<ImmutableObjectInitializer *>(
            InitManager::instance.findInitializer(*this)
        );
        if (!initializer) {
            return {};
        }

        ObjectSharedPtr object;
        return initializer->tryGetObjectAt(fieldId.getIndexAndOffset(), object) ? object : ObjectSharedPtr();
    }

    ObjectImmutableImpl::ObjectSharedPtr ObjectImmutableImpl::get(const char *fieldName) const
    {
        auto obj = tryGet(fieldName);
        if (!obj) {
            if (this->isDropped()) {
                THROWF(db0::InputException) << "Object is no longer accessible";
            }
            THROWF(db0::InputException) << "Attribute not found: " << fieldName;
        }
        return obj;
    }

    void ObjectImmutableImpl::getMembersImpl(std::unordered_set<std::string> &result) const
    {
        super_t::getMembersImpl(result);
        auto &objType = this->getType();
        for (const auto &entry: (*this)->field_map()) {
            std::uint32_t index = 0;
            if (entry.key().itemKind() == StorageClass::PACKED_INT32) {
                index = entry.key().packedIntPayload().value();
            } else if (entry.key().itemKind() == StorageClass::INT64) {
                index = static_cast<std::uint32_t>(entry.key().intPayload().value());
            } else {
                continue;
            }
            result.insert(objType.getMember(FieldID::fromIndex(index)).m_name);
        }
    }
    
}
