#pragma once

#include <cstddef>
#include <Python.h>
#include "PyWrapper.hpp"

namespace db0::object_model

{
    
    class Object; 
    
}

namespace db0::python

{
    
    using MemoObject = PyWrapper<db0::object_model::Object>;
    
    PyTypeObject *wrapPyType(PyTypeObject *, bool is_singleton);
    PyObject *wrapPyClass(PyObject *self, PyObject *, PyObject *kwargs);
    
    MemoObject *MemoObject_new(PyTypeObject *type, PyObject * = nullptr, PyObject * = nullptr);
    // create a memo object stub
    MemoObject *MemoObjectStub_new(PyTypeObject *type);
    PyObject *MemoObject_alloc(PyTypeObject *type, Py_ssize_t nitems);
    
    void MemoObject_del(MemoObject* self);
    void MemoObject_drop(MemoObject* self);
    int MemoObject_init(MemoObject* self, PyObject* args, PyObject* kwds);
    PyObject *MemoObject_getattro(MemoObject *self, PyObject *attr);
    int MemoObject_setattro(MemoObject *self, PyObject *attr, PyObject *value);
    
    // check for a memo type (i.e. generated by wrapPyClass)
    bool PyMemo_Check(PyObject *obj);
    bool PyMemoType_Check(PyTypeObject *type);
    
    // check if memo type has been marked as singleton
    bool PyMemoType_IsSingleton(PyTypeObject *type);
    
    PyObject *MemoObject_GetFieldLayout(MemoObject *);
    
    PyObject *MemoObject_DescribeObject(MemoObject *);
    PyObject *MemoObject_IsTag(PyObject *self, PyObject *const *args, Py_ssize_t nargs);
    PyObject *MemoObject_str(MemoObject *);
}