#pragma once

#include <cstddef>
#include <Python.h>
#include "PyWrapper.hpp"
#include <atomic>
#include "shared_py_object.hpp"

namespace db0::object_model

{
    
    class Object; 
    
}

namespace db0::python

{
    
    struct MemoTypeDecoration
    {
        const char *m_prefix_name_ptr = 0;
        const char *m_type_id = 0;
        // resolved fixture UUID (initialized by the process)
        std::atomic<std::uint64_t> m_fixture_uuid = 0;    
        
        MemoTypeDecoration(const char *prefix_name, const char *type_id);
        std::uint64_t getFixtureUUID();
        void close();
    };

    using MemoObject = PyWrapper<db0::object_model::Object>;
    
    PyTypeObject *wrapPyType(PyTypeObject *, bool is_singleton, const char *prefix_name, const char *type_id);
    PyObject *wrapPyClass(PyObject *self, PyObject *, PyObject *kwargs);
    
    MemoObject *MemoObject_new(PyTypeObject *type, PyObject * = nullptr, PyObject * = nullptr);
    // create a memo object stub
    shared_py_object<MemoObject*> MemoObjectStub_new(PyTypeObject *type);
    PyObject *MemoObject_alloc(PyTypeObject *type, Py_ssize_t nitems);
    
    void MemoObject_del(MemoObject* self);
    void MemoObject_drop(MemoObject* self);
    int MemoObject_init(MemoObject* self, PyObject* args, PyObject* kwds);
    PyObject *MemoObject_getattro(MemoObject *self, PyObject *attr);
    int MemoObject_setattro(MemoObject *self, PyObject *attr, PyObject *value);
    // check for equal instances - i.e. if fixture and address are the same
    bool isEqual(MemoObject *, MemoObject *);

    // check for a memo type (i.e. generated by wrapPyClass)
    bool PyMemo_Check(PyObject *obj);
    bool PyMemoType_Check(PyTypeObject *type);
    
    // check if memo type has been marked as singleton
    bool PyMemoType_IsSingleton(PyTypeObject *type);
    
    PyObject *MemoObject_GetFieldLayout(MemoObject *);
    
    PyObject *MemoObject_DescribeObject(MemoObject *);
    PyObject *MemoObject_IsTag(PyObject *self, PyObject *const *args, Py_ssize_t nargs);
    PyObject *MemoObject_str(MemoObject *);
    
    void PyMemoType_get_info(PyTypeObject *type, PyObject *dict);
    void PyMemoType_close(PyTypeObject *type);
    
    PyObject *PyMemo_set_prefix(MemoObject *, const char *prefix_name);
    
}